#!/bin/bash
set -e

echo -n "Checking format... "
changed_go_files=`git diff --cached --name-only *.go`
if [[ -n "$changed_go_files"  && "$(gofmt -s -l ${changed_go_files} | wc -l)" -gt 0 ]]; then
    echo "FAIL"
    echo ""
    echo "Found formatting errors in these files:"
    gofmt -s -l ${changed_go_files}
    exit 1;
fi
echo "OK"

echo "Ready to commit!"