#!/bin/bash
set -e

echo -n "Checking format... "
if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then
    echo "FAIL"
    echo "Found formatting errors. Please run gofmt to check and fix them."
    exit 1;
fi
echo "OK"

echo "Running tests..."
go test -v

echo "Ready to commit!"