# GENERAL CONFIGURATION

name = "core-automator"
runs = 2
# runs = ["alpha", "beta"]

[monitor]
pidstat = 0
pidstat_params = "vnoded"
net = 0
net_params = "eth0"
xy = 1
xy_params = "5"
contacts = 1
contacts_params = "5"

[times]
warmup = 5
runtime = [30, 60]

[procs]
exec = [["""
echo started > started.log
""", """
echo second > second.log
"""]]
daemonized = [["goforban serve", "periodic-file-generator bin 64 512 15 40 var/share"]]
shutdown = [["goforban", "periodic-file-generator"]]

[logging]
collect_everything = true

[hooks]
pre = ["""
echo "pre hook - results from run 0 in $1" > pre.txt
""",
"""
echo "pre hook - results from run 1 in $1" > pre.txt
"""]
start = """
echo "start hook - results in $1" > start.txt
"""
post = """
echo "post hook - results in $1" > post.txt
"""
analyze = """
echo "post hook - results in $1" > post.txt
"""

# SCENARIO

[[networks]]
_runs = [0]
id = 5
name = "AdHocWiFi"
type = "WIRELESS_LAN"
x = 62
y = 157
lat = 47.57773960399303
lon = -122.13148656678577
alt = 2.0



[[devices]]
id = 1
name = "n1"
type = "PC"
class = ""
image = ""
position = {x=[496, 296], y=464, lat=47.57494892806669, lon=-122.12563853428615, alt=2.0}

[[devices.services]]
name = "DefaultRoute"



[[links]]
node1 = 5
node2 = 1
id = 0
name = "eth0"
mac = "00:00:00:aa:00:05"
ip4 = "10.0.0.20"
ip4_mask = 24
ip6 = "2001::20"
ip6_mask = 128

[[links]]
node1 = 5
node2 = 2
name = "eth0"
mac = "00:00:00:aa:00:06"
ip4 = "10.0.0.21"
ip4_mask = 24
ip6 = "2001::21"
ip6_mask = 128

[[links]]
_runs = [1]
node1 = 5
node2 = 3
name = "eth0"
mac = "00:00:00:aa:00:07"
ip4 = "10.0.0.22"
ip4_mask = 24
ip6 = "2001::22"
ip6_mask = 128



[[mobility_configurations]]
node = 5
model = "basic_range"

[mobility_configurations.configuration]
range = 180
bandwidth = 54000000
jitter = 0
delay = 20000
error = 0
promiscuous = 0



[[emane_global_configuration]]
emulator = true

[emane_global_configuration.core]
platform_id_start = 1
nem_id_start = 1
link_enabled = [false, true]
loss_threshold = 30
link_interval = 1
link_timeout = 4


[session_origin]
lat=47.5791667
lon=-122.132322
alt=2.0
scale=150.0


[session_options]
controlnet  = ""
controlnet0 = ""
controlnet1 = ""
controlnet2 = ""
controlnet3 = ""
controlnet_updown_script = ""
enable_rj45 = true
preserve_dir = false
enable_sdt = false
sdt_url = "tcp://127.0.0.1:50000/"
ovs = "0"

[session_metadata]
canvas_c1 = "{name {Canvas1}}"
global_options = """
interface_names=no
ip_addresses=yes
ipv6_addresses=no
node_labels=yes
link_labels=yes
show_api=no
background_images=no
annotations=yes
grid=yes
traffic_start=0
"""

[[default_services]]
type = "mdr"

[[default_services.services]]
name = "zebra"

[[default_services.services]]
name = "OSPFv3MDR"

[[default_services.services]]
name = "IPForward"

[[default_services]]
type = "PC"

[[default_services.services]]
name = "DefaultRoute"

[[default_services]]
type = "prouter"

[[default_services]]
type = "router"

[[default_services.services]]
name = "zebra"

[[default_services.services]]
name = "OSPFv2"

[[default_services.services]]
name = "OSPFv3"

[[default_services.services]]
name = "IPForward"

[[default_services]]
type = "host"

[[default_services.services]]
name = "DefaultRoute"

[[default_services.services]]
name = "SSH"



# MOVEMENT PATTERN
[movement_pattern]
type = "input"
pattern = """
%delay 10.0

n1 50 50 
n2 400 400
n3 750 50
-- STEP

n2 100 50
-- STEP

n2 700 50
-- STEP
"""

