Name = "A very simple experiment"
Targets = ["coreemu-lab", "The ONE"]
RandomSeed = 2502352939705136212

Duration = 240

[[Network]]
Name = "Wifi"
Type = "WirelessLAN"

[[NodeGroup]]
Prefix = "users"
NoNodes = 7
Networks = ["Wifi"]