# An example to demonstrate the use of different movement patterns with netlab.
#
# This configuration will create one network as well as five groups of nodes,
# each of which uses as different movement model. For the movements itself,
# default values are used. See documentation for more information on those.

Name = "Different Movement Patterns"
Runs = 1
RandomSeed = 7850800065078565476
Targets = ["coreemu-lab", "The ONE"]

Duration = 240
Warmup = 5

WorldSize.Height = 1000
WorldSize.Width = 1500


[[Network]]
Name = "Wifi"
Type = "WirelessLAN"
Bandwidth = 54000000
Range = 600

[[NodeGroup]]
Prefix = "static"
NoNodes = 4
MovementModel = "static"
Networks = ["Wifi"]

[[NodeGroup]]
Prefix = "rwp"
NoNodes = 4
MovementModel = "Random Waypoint"
Networks = ["Wifi"]

[[NodeGroup]]
Prefix = "fast_rwp"
NoNodes = 4
MovementModel = "Random Waypoint"
Networks = ["Wifi"]
MinSpeed = 30
MaxSpeed = 100
MaxPause = 1