Name = "Multiple Networks & Groups"
Runs = 1
RandomSeed = 7850800065078565476
Targets = ["coreemu-lab", "The ONE"]

Duration = 240
Warmup = 5

WorldSize.Height = 1000
WorldSize.Width = 1500


[[Network]]
Name = "Wifi 2.4GHz"
Type = "WirelessLAN"
Bandwidth = 54000000
Range = 200

[[Network]]
Name = "Wifi 5GHz"
Type = "WirelessLAN"
Bandwidth = 1300000000
Range = 80

[[Network]]
Name = "LTE"
Type = "WirelessLAN"
Bandwidth = 250000000
Range = 800


[[NodeGroup]]
Prefix = "laptops"
NoNodes = 7
NodeType = "PC"
Networks = ["Wifi 2.4GHZ", "Wifi 5GHz"]

[[NodeGroup]]
Prefix = "IoT"
NoNodes = 12
NodeType = "PC"
Networks = ["Wifi 2.4GHz"]

[[NodeGroup]]
Prefix = "smartphones"
NoNodes = 12
NodeType = "PC"
Networks = ["Wifi 2.4GHz", "Wifi 5GHz", "LTE"]
MovementModel = "RandomWaypoint"