name: Sprint tests

on:
  schedule:
    # Run every tuesday on 10:00 UTC (11:00 CET)
    - cron: "0 10 * * 2"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Formatter
        run: if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi

      - name: Build
        run: go build -v ./...

      - name: Unit Tests
        run: go test -v ./...
