name: Unit tests & static analysis

on: [push]

jobs:
  static-analysis:
    name: Static analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Formatter
        run: if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi

      - name: Go Vet
        run: go vet ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          cache: true

      - name: Coverage
        run: go test -v -coverpkg=./... -coverprofile=profile.cov ./... && go tool cover -func profile.cov
          
  build-test:
    name: Build & test
    strategy:
      fail-fast: false
      matrix:
        os: ["windows-latest", "ubuntu-latest", "macOS-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          cache: true

      - name: Build
        run: go build -o netlab -v

      - name: Test
        run: go test -v ./...

      - name: Upload executable
        uses: actions/upload-artifact@v3
        with:
          name: netlab-${{ matrix.os }}
          path: netlab
